In [2]:
import numpy as np

### Simplex Method
An efficient way of finding the optimal solution is to use the simplex method, which is an algorithm that adjusts the values of non-basic variables to move from one vertex to an adjacent vertex. It uses pivot operation (recall matrix operations) and exchange a non-basic variable to increase the objective function with a basic variable, changing the current vertex of the polytope.
* The method is different than the brute force method of finding all vertices because it focuses on optimizing the objective function

Key terms:
1. dictionary/tableau: representation of the linear programming problem
$$
T =
\begin{bmatrix}
A & I & \mathbf{b} \\
\mathbf{c}^T & 0 & 0
\end{bmatrix}
$$
2. slack variables: introduced to convert inequalities into equalitites in the constraints.
3. Basic variables: variables whose values are determined by the system
4. Non-basic variables: variables that are typically set to zero in the current basic feasible solution
5. convex polytope: intersection of half-spaces defined by linear constraints

#### Slack Variables

$$
\begin{array}{rc}
\text{maximize:} & c_0x_0 + \cdots + c_{n-1}x_{n-1} \\
\text{subject to:} & a_{0,0}x_0 + \cdots + a_{0,n-1}x_{n-1} + w_0 = b_0 \\
& a_{1,0}x_0 + \cdots + a_{1,n-1}x_{n-1} + w_1 = b_1 \\
& \vdots \\
& a_{m-1,0}x_0 + \cdots + a_{m-1,n-1}x_{n-1} + w_{m-1} = b_{m-1} \\
& x_0 \geq 0, \dots , x_{n-1} \geq 0, w_0 \geq 0, \dots , w_{m-1} \geq 0
\end{array}
$$

$$
[ \ A \ I \ ] \begin{bmatrix} \mathbf{x} \\ \mathbf{w} \end{bmatrix} = \mathbf{b}
$$


The following is a matrix used in simplex method for solving linear programming problems.
$$
T =
\begin{bmatrix}
A & I & \mathbf{b} \\
\mathbf{c}^T & 0 & 0
\end{bmatrix}
$$

* $\mathbf{A}$ : represents the coefficient matrix of the constraints
* $\mathbf{I}$ : used to identify basic variables
* $\mathrm{b}$ : right-hand side value of the constraints
* $\mathbf{A}$ and $\mathbf{I}$ form the matrix of the coefficients for the basic and non-basic variables
* ($\mathrm{c}^T$, 0, 0) : serves to track the current objective function value

### Pivot Operation in Simplex Method

Vanderbei exercise 2.3

maximize $2x_1 - 6x_2\\$
subject to $-x_1 - x_2 -x_3 \leq -2\\$
$\qquad \qquad 2x_1 - x_2 + x_3\leq 1\\$
$\qquad \qquad x_1, x_2, x_3\geq 0$

The auxiliary problem is 

maximize $-x_0\\$
subject to $-x_1 - x_2 -x_3 - x_0 \leq -2\\$
$\qquad \qquad 2x_1 - x_2 + x_3 -x_0\leq 1\\$
$\qquad \qquad x_0, x_1, x_2, x_3\geq 0$

From the initial dictionary, we have:

$\zeta = -x_0\\$
$w_1 = -2 + x_1 + x_2 + x_3 + x_0\\$
$w_2 = 1 - 2x_1 + x_2 - x_3 + x_0\\$

We only have $x_0$ to be the entering variable and the most infeasible variable is $w_1$ leaving the basis variable:

$\zeta = - 2 - w_1 + x_1 + x_2 + x_3\\$
$x_0 = 2 + w_1 -x_1 - x_2 - x_3\\$
$w_2 = 1 - 2x_1 + x_2 - x_3 \\$

Rearranging the dictionary, we rewrite in standard form, letting $w_1$ and $w_2$ be $w_1$ and $w_2$ respectively:

$\zeta = - 2 + x_1 + x_2 + x_3 - x_4\\$
$x_0 + x_1 + x_2 + x_3 - x_4 \quad = 2\\$
$2x_1 - x_2 + x_3 \quad + x_5 = 1\\$


We consider $x_0$ as decision variable instead of slack variable.

$\mathbf{A} =
\begin{bmatrix}
1 & 1 & 1 & 1 \\
0 & 2 & -1 & 1 \\
\end{bmatrix}$
$\mathbf{I} =
\begin{bmatrix}
-1 & 0\\
0 & 1
\end{bmatrix}$
$\mathbf{b} =
\begin{bmatrix}
2\\
1
\end{bmatrix}$

$\mathbf{c}^T = \begin{bmatrix}
0 & 1 & 1 & 1 & -1 & 0 & -2
\end{bmatrix}$

$$
T =
\begin{bmatrix}
1 & 1 & 1 & 1 & -1 & 0 & 2\\
0 & 2 & -1 & 1 & 0 & 1 & 1\\
0 & 1 & 1 & 1 & -1 & 0 & -2
\end{bmatrix}
$$

### Pivot Operation

The basic feasible solution is the solution obtained by setting the non-basic variables to zero. From the initial dictionary, the basic feasible solution is -2 because we set $x_1$, $x_2$, $x_3$ and $x_4$, the non-basic variables, to 0. Since we want to maximize the objective function, we need to choose the entering variable, from non-basic variable to the basic. Among the non-basic variable, $x_1$, $x_2$, and $x_3$ find the highest coefficient, otherwise find the smallest subscript. So, $x_1$ is the entering variable.

By increasing $x_1$ by one unit, we have the following by setting $x_2$, $x_3$ and $x_4$ to 0:
$$x_0 = 2 - x_1 \geq 0 \qquad x_5 = 1 - 2x_1 \geq 0$$
and thus,
$$x_1 \leq 2 \qquad x_1 \leq 1/2$$

Since all the constraints need to be satisfied, $x_1$ cannot be larger than $\frac{1}{2}$. Thus, the formula for choosing the leaving variable is picking i from:
$$x_k = \text{min}_{i \in B: a_{ik} > 0} b_i/a_{ik}$$

Thus, the leaving variable is $x_5$. 

In [3]:
A = np.array([[1, 1, 1, 1], [0, 2, -1, 1]])
m,n = A.shape
I = np.array([[-1, 0], [0, 1]])
b = np.array([2, 1])
c = np.array([0, 1, 1, 1, -1, 0, -2])
T = np.vstack([np.hstack([A, I, b.reshape((m, 1))]), c])
print(T)

[[ 1  1  1  1 -1  0  2]
 [ 0  2 -1  1  0  1  1]
 [ 0  1  1  1 -1  0 -2]]


In [4]:
def pivot(T,k,l):
    E = np.eye(T.shape[0])
    E[:,l] = -T[:,k]/T[l,k]
    E[l,l] = 1/T[l,k]
    return E@T

We see that column $k = 1$ has the largest positive entry and the minimum subscript. 

$\frac{T_{0, 6}}{T_{0, 1}}= 2/1$

$\frac{T_{1, 6}}{T_{1, 1}}= 1/2$

Since the ratio for $i=1$ is positive and minimal we choose $\ell=1$.

In [5]:
T1 = pivot(T, 1, 1)
print(T1)

[[ 1.   0.   1.5  0.5 -1.  -0.5  1.5]
 [ 0.   1.  -0.5  0.5  0.   0.5  0.5]
 [ 0.   0.   1.5  0.5 -1.  -0.5 -2.5]]


We see that column $k = 2$ has the largest positive entry.

$\frac{T_{0, 6}}{T_{0, 2}}= 1.5/1.5$

$\frac{T_{1, 6}}{T_{1, 2}}= 0.5/-0.5$

Since the ratio for $i = 0$ is positive, we choose $\ell=0$.

In [6]:
T2 = pivot(T1, 2, 0)
print(np.round(T2, 3))

[[ 0.667  0.     1.     0.333 -0.667 -0.333  1.   ]
 [ 0.333  1.     0.     0.667 -0.333  0.333  1.   ]
 [-1.     0.     0.     0.     0.     0.    -4.   ]]


The algorithm will stop when all variable at the objective function has negative coefficient. 